### ISSUE TITLE
Define minimum requirements

### ISSUE THREAD

**Issue by cmungall** [INCATools/obographviz#23]
the sequence

```
docker run  -v $PWD:/work -w /work -ti node bash
npm install -g obographviz
og2dot --help
```

works with latest node, but when I try with ODK:

```
✗ docker run  -v $PWD:/work -w /work -ti obolibrary/odkfull bash
root@19138ca8b3c3:/work# node --version
v10.19.0
root@19138ca8b3c3:/work# npm install -g obographviz
/usr/local/bin/og2dot -> /usr/local/lib/node_modules/obographviz/bin/og2dot.js
npm WARN notsup Unsupported engine for obographviz@0.4.1: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: obographviz@0.4.1
npm WARN notsup Unsupported engine for commander@9.3.0: wanted: {"node":"^12.20.0 || >=14"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: commander@9.3.0

+ obographviz@0.4.1
added 8 packages from 8 contributors in 1.598s
root@19138ca8b3c3:/work# og2dot --help
/usr/local/lib/node_modules/obographviz/bin/og2dot.js:3
import { readFileSync, existsSync, writeFileSync } from 'fs';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

seems odd it perseveres and installs anyway - but we should document - in package.json the minimum reqs. 12 or 14?

**Comment by pkalita-lbl** [comment]
12 is the minimum. It is in [package.json](https://github.com/INCATools/obographviz/blob/master/package.json#L18) which is why you get the warning on install. But it is just that -- a warning -- unless the user has configured their setup to be more [strict](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines). We build and test with 12, 14, and 16 ([for example](https://github.com/INCATools/obographviz/actions/runs/2632667741)) even though technically 12 isn't even on [maintenance](https://nodejs.org/en/about/releases/) anymore. I will add it to the README as well, just to be as clear as possible.

I'm also a little surprised about your experience with the `obolibrary/odkfull` image because I had tested using that image yesterday. When I run the latest version of that image I see Node 12.x:

```shell
~ 
➜ docker pull obolibrary/odkfull:latest
latest: Pulling from obolibrary/odkfull
Digest: sha256:272d3f788c18bc98647627f9e6ac7311ade22f35f0d4cd48280587c15843beee
Status: Image is up to date for obolibrary/odkfull:latest
docker.io/obolibrary/odkfull:latest

~ 
➜ docker run -it obolibrary/odkfull bash
root@469b4a43ef86:/tools# node --version
v12.22.9
root@469b4a43ef86:/tools# 
```
